version: "3"

services:
  api:
    container_name: intelligence-type-classifier-api
    build: .
    restart: always
    ports:
      - 8000:80
    env_file:
      - .env
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db
